### ISSUE TITLE
Audit hangs on retrieving vulnerabilities for pnpm workspace

### ISSUE THREAD

**Issue by gabidobo** [sandworm-hq/sandworm-audit#130]
I tried to run it on my production project, but sandworm just stuck on `Getting vulnerability report from pnpm` stage for some reason 🤔 

<img width="379" alt="image" src="https://github.com/sandworm-hq/sandworm-audit/assets/9947582/304e20b7-73c2-4302-801a-9651f42fae2e">

_Originally posted by @acherkashin in https://github.com/sandworm-hq/sandworm-audit/discussions/101#discussioncomment-6819820_

**Comment by gabidobo** [comment]
@acherkashin weird behaviour 🤔 

Could you please also try running `pnpm audit --json` in the same directory, see if that also hangs or errors out?

**Comment by gabidobo** [comment]
I was able to replicate this with pnpm 8.7.4 - looks connected to [this pnpm issue](https://github.com/pnpm/pnpm/issues/6465).

**Comment by acherkashin** [comment]
Sorry for the late reply.

`pnpm audit --json` works well and doesn't print any errors 

My pnpm version is `7.17.1`
