### ISSUE TITLE
Support custom/private registries

### ISSUE THREAD

**Issue by gabidobo** [sandworm-hq/sandworm-audit#50]

**Comment by bluthen** [comment]
Sorry if this is the wrong way to discuss. Could a possible way to support this be to allow resolved-issues.json to have an empty id, and only path,note? An empty id could be like a wildcard for all issues with that path.

I suppose that would mean "resolve" would need extra arguments if you don't want people just directly editing the resolved-issues.json file.

Great project BTW!
