### ISSUE TITLE
`Building dependency graph...` never finishes

### ISSUE THREAD

**Issue by n1kk** [sandworm-hq/sandworm-audit#62]
**Sandworm version**
Can't get, running `sandworm-audit -v` starts building dependency graph again. Just installed it today.

**Describe the bug**
`Building dependency graph...` never finishes, even after 10-15 minutes. No excessive CPU/RAM usage. Tried running with `--from disk` same. 

I'm running it in an environment with proxy and we use a custom npm registry mirror to not get blacklisted by npm for excessive amount of requests. All the settings are in the npm config. 

**To Reproduce**
Just installed it and ran `sandworm-audit`

**Expected behavior**
A message of why it's taking so long would be nice, or a check for a race condition if it's a network call that is never resolved or something like that.

**System (please complete the following information):**
- Node Version v18.13.0
- Package Manager npm
- Package Manager Version 9.2.0
- OS: Windows 10

**Additional context**

**Comment by andreimarinescu** [comment]
Hey, @n1kk. Thanks for submitting this issue! Overall, the building dependency graph can take a lot of time, depending on the state of the NPM registry load.

Would you mind testing with the latest version released today, specifically `1.3.0`? We've added a progress indicator that should clarify if the job is indeed stuck. We've also added a few performance improvements that could also help.

One final note: running `sandworm-audit -v` is only supported starting with `1.3.0`.

**Comment by gabidobo** [comment]
As an update here, custom registries are now supported starting with v1.36.0.
